name: Deploy to Netlify

on:
  push:
    branches:
      - main  # adjust to your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd Frontend/my-trade  # Navigate to your frontend directory
          npm install

      - name: Build the app
        run: |
          cd Frontend/my-trade  # Navigate to your frontend directory
          npm run build

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}  # Add this secret in your GitHub repository settings
        run: |
          npm install -g netlify-cli
          netlify deploy --prod --dir=./build --auth=$NETLIFY_AUTH_TOKEN  # Specify the build directory relative to the current directory
