name: Deploy to Netlify

on:
  push:
    branches:
      - main  # adjust to your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Build and deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}  # Use the secret here
        run: |
          npm install
          npm run build
          netlify deploy --prod --dir=./build --auth=$NETLIFY_AUTH_TOKEN
